<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ConnectedComponents</RootNamespace>
    <AssemblyName>ConnectedComponents</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Optimize>true</Optimize>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <StartupObject>ConnectedComponents.Cli.Program</StartupObject>
  </PropertyGroup>

</Project>
